### ISSUE TITLE
Не устанавливается

### ISSUE THREAD

**Issue by Ultra119** [SanyaPilot/pmos-firmware-xiaomi-tucana#1]
Скачал ети файлы на телефон   распоковал в главную папку в MI Проводник   но чит на бравл старс не работайет      Помогите как делать нада ?

**Comment by SanyaPilot** [comment]
А вот пока не время устанавливать!!!

**Comment by Ultra119** [comment]
скажи пожалуста када будет читы уже ??    мне надо 20000 кубков дабить

**Comment by SanyaPilot** [comment]
не будет!!!
